# -*- coding: utf-8 -*-
# This tool is used to delete null files generated by https://github.com/microsoft/vscode-cpptools/issues/9046
# You can use function 'non_recursive_check' or 'recursive_check' by changing the code.
# To avoid delete useful null files, I added posix times check.
# Before use it, I hope you to know risk of it.
# Linux OS Environment has been tested.

import os
import sys

def del_wrong_null_file(filename):
    size = os.path.getsize(filename)
    t = os.path.getctime(filename)
    print('test', size, t)

    # 1647446400 = 2022-03-17 0:0:0
    if size == 0 and t > 1647446400:
        # print('remove', size, t)
        os.remove(filename)

def recursive_check(path):
    for parent, dirnames, filenames in os.walk(path):
        for filename in filenames:
            new_path = os.path.join(parent, filename)
            del_wrong_null_file(new_path)
    pass

def non_recursive_check(path):
    for filename in os.listdir(path):
        del_wrong_null_file(filename)
    pass

if __name__ == '__main__':
    deal_path = '.'
    non_recursive_check(deal_path)
    # recursive_check(deal_path)
    pass